### ISSUE TITLE
Focus states do not line up

### ISSUE THREAD

**Issue by alex-page** [govau/design-system-site#388]
# Bug report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-site/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-site/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

As pointed out on HackerNews by dbg31415 our focus states are not lining up in certain areas.

## What I expected to happen

Focus states should be clean squares around elements.

## Attachments

https://imgur.com/a/t0iwmWi

**Comment by sukhrajghuman** [comment]
So the reason this is happening is because the icon has a height greater than the font-size (1.25em). Also this is only happening on chrome.

According to the w3 specification for using the [outline property](https://www.w3.org/TR/CSS2/ui.html#propdef-outline).
"Outlines may be non-rectangular...but they should be connected".

I've tried in Firefox, chrome and safari and here is a link to a codepen: https://codepen.io/sukhrajghuman/pen/pGZjjY

**Firefox**: the focus outline rectangle matches the large of the `:before` text vs the anchor tag text

![image](https://user-images.githubusercontent.com/20184809/52753775-2b15af80-304c-11e9-9d74-fc70d26ca4a7.png)

**Safari**: the focus outline rectangle height matches the anchor text 

![image](https://user-images.githubusercontent.com/20184809/52753884-98c1db80-304c-11e9-8ad7-b540538c38aa.png)

**Chrome**: the focus outline rectangle matches height of all text.

![image](https://user-images.githubusercontent.com/20184809/52753966-d45ca580-304c-11e9-979d-f77e551c1507.png)

None of these are incorrect since they meet the specification. But for a consistent solution, will need to apply `display: inline-block` to the anchor tag

**Comment by sukhrajghuman** [comment]
We'll just need to add a `margin-left` to this one since the `border-bottom` is interfering with the focus outline
![image](https://user-images.githubusercontent.com/20184809/52754442-a4160680-304e-11e9-91c4-3a1fc7b1e57e.png)

**Comment by adamzerella** [comment]
This has been resolved as of: https://github.com/govau/design-system-site/commit/cae021d5cbb1631db686fed01cfd969f13eedbfe
